### ISSUE TITLE
Select cities

### ISSUE THREAD

**Issue by nynkevoermans** [course-dprep/team-assignment-team-6#15]
We need to select cities that we want to compare and include in the dataset. We think we want to compare cities from the top 5 countries with the highest and the lowest inflation.

**Comment by nynkevoermans** [comment]
We selected the following cities as the high inflation cities:
1. Rio de Janeiro
2. Mexico City
3. Boston
4. Cape Town
5. Santiago

We selected the following cities as the low inflation cities:
1. Tokyo
2. Geneva
3. Beijing 
4. Bangkok
5. Athens

Source used: https://www.theglobaleconomy.com/rankings/inflation/

**Comment by amber-kalse** [comment]
Nynke Voermans closed this Issue
